<robot name="mycamera" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- camera 部件 -->
    <!-- 1.参数 -->
    <!-- 
        参数：
            连杆属性：厚度，宽度，高度
            关节属性：x y z
     -->
    <xacro:property name="camera_length" value="0.02" /> <!-- 摄像头长度(x) -->
    <xacro:property name="camera_width" value="0.05" /> <!-- 摄像头宽度(y) -->
    <xacro:property name="camera_height" value="0.05" /> <!-- 摄像头高度(z) -->
    <xacro:property name="camera_mass" value="0.01" /> 
    <xacro:property name="joint_camera_x" value="0.08" /> <!-- 摄像头安装的x坐标 -->
    <xacro:property name="joint_camera_y" value="0" /> <!-- 摄像头安装的y坐标 -->
    <xacro:property name="joint_camera_z" value="${base_length / 2 + camera_height / 2}" />
    <!-- 2.设计连杆和关节 -->
    <!-- link -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>

            <material name="black">
                <color rgba="0 0 0 0.8" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <!-- 调用惯性矩阵 -->
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
    </link>
    <gazebo reference="camera">
        <material>Gazebo/Red</material>
    </gazebo>
    <!-- joint -->
    <joint name="camera2base" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy=" 0 0 0" />
    </joint>
</robot>