<robot name="carbase" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="footprint_radius" value="0.0001" />
    <!-- 1.添加 base_footprint -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>

    <!-- 2.添加底盘 -->
    <!-- 
        形状：圆柱
        半径：0.1m
        高度：0.08m
        离地间距：0.015m
     -->
    <!-- <xacro:property name="base_radius" value="0.1" /> -->
    <xacro:property name="base_length" value="0.23" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:property name="base_joint_z" value="${base_length / 2 + lidi}" />
    <!-- 2-1.link -->
    <link name="base_link">
    <visual>
        <geometry>
            <!-- <box size="0.5 0.25 0.23"/> -->
            <cylinder radius="0.1" length="0.08" />
        </geometry>

        <origin xyz="0 0 0" rpy="0 0 0" />

        <material name="baselink_color">
            <color rgba="1.0 0.5 0.2 0.5" />
        </material>
    </visual>
    </link>
    <!-- 2-2.joint -->
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <!-- z = 车体高度/2 + 离地间距 -->
        <origin xyz="0 0 0.055" rpy="0 0 0" />

    </joint>

    <!-- 3.添加驱动轮 -->
    <!-- 
        形状：圆柱
        半径：0.0325m
        长度：0.015m
     -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="wheel_joint_z" value="${( base_length / 2 + lidi - wheel_radius) * -1}" />
    <!-- 
        wheel_name: left or right
        flag: 1 or -1
     -->
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <!-- 3-1.link -->
        <!-- ${wheel_name} -->
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>

                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />

                <material name="wheel_color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>
        
        <!-- 3-2.joint -->
        <!-- ${wheel_name}_wheel -->
        <joint name="${wheel_name}2link" type="continuous">
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <!-- 
                x = 0
                y = 车体半径
                z = -(车体高度/2 + 离地间距 - 车轮半径)
            -->
            <origin xyz="0 ${0.1 * flag} ${wheel_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <!-- 调用 -->
    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />

    <!-- 4.添加万向轮 -->
    <!-- 
        形状：球
        半径：0.0075m
     -->
    <xacro:property name="small_wheel_radius" value="0.0075" />
    <xacro:property name="small_joint_z" value="${( base_length / 2 + lidi - small_wheel_radius) * -1}" />
    <!-- 4-1.link -->
    <!-- front_wheel -->
    <xacro:macro name="small_wheel_func" params="small_wheel_name small_flag" >
        <link name="${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="0.0075" />
                </geometry>

                <origin xyz="0 0 0" rpy="0 0 0" />

                <material name="wheel_color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>
        <!-- 4-2.joint -->
        <!-- front_wheel -->
        <joint name="${small_wheel_name}2link" type="continuous">
            <parent link="base_link" />
            <child link="${small_wheel_name}_wheel" />
            <!-- 
                x = 0
                y = 车体半径
                z = -(车体高度/2 + 离地间距 - 万向轮半径)
            -->
            <origin xyz="${0.08 * small_flag} 0 ${small_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <xacro:small_wheel_func small_wheel_name="front" small_flag="1" />
    <xacro:small_wheel_func small_wheel_name="back" small_flag="-1" />

</robot>